services:
  - type: web
    name: maziwasmart
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENABLE_UPLOAD_HEADERS
        value: "true"
